### ISSUE TITLE
How to connect to a server?

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-xmpp#3]
You can check out Hyperchannel's `feature/41-xmpp_support` branch, where I'm trying to connect to a server. Unfortunately I don't know how this is supposed to work, and trying the same as what we're doing with IRC also doesn't help (emit `credentials` instead of `connect`):

https://github.com/67P/hyperchannel/blob/feature/41-xmpp_support/app/services/sockethub-xmpp.js#L21-L45

There's no log entry in the Sockethub debug logs and no Websocket response after emitting this object.

**Comment by silverbucket** [comment]
Credentials should be sent along the credentials channel, it looks like thats not whats happening in the link you sent me. There's also a basic example at: https://github.com/sockethub/sockethub/blob/master/views/examples/xmpp.ejs

**Comment by skddc** [comment]
Doesn't change anything:

> trying the same as what we're doing with IRC also doesn't help (emit credentials instead of connect)

**Comment by silverbucket** [comment]
@skddc the connection process is slightly different as with XMPP you have to authenticate yourself before you can do anything else. Did you compare the example with what you're doing in hyperchannel?

**Comment by skddc** [comment]
The example is very contrived. It would really help to just explain how one connects to a server.

**Comment by skddc** [comment]
The way I read the code is that one has to emit a `credentials` job with a credentials object and then send a message of type "connect" with the same credentials, but a slightly different object, after that?

**Comment by silverbucket** [comment]
Contrived? Not sure what you mean by that. It connects to a server... doesn't do much other than that. I plan on making docs, but had this ready for testing several months ago and now I will need to find time to revisit it and write docs, I don't just have it all still on the top of my head. So if you want to know ASAP just check out the example.

**Comment by silverbucket** [comment]
@skddc Yeah, though not with the same credentials, just with a reference to the credentials. Thats what the AS module does.

**Comment by skddc** [comment]
Sorry, might be the wrong word. I'm not a native speaker. I meant that it's hard to read, as things are all Sockethub-specific and not in functions called "connect" or similar. So if you don't know how things work in SH in the first place, it's hard to read and understand.

It's not just that the XMPP docs are missing, but there are literally zero docs on Sockethub usage that I could find. The wiki (which is also linked prominently from the website) has a page for installation, but the usage/app dev section links to non-existing pages: https://github.com/sockethub/sockethub/wiki#app-developers

So it's just hard to learn what one is supposed to do in general.

I'll try it again with the exact code from the example, and hope I can then find out how to do the rest of the things we need to implement. Thanks.

**Comment by skddc** [comment]
So, I finally managed to get a successful connect from our 5apps server. But then I looked at the example to see how to do anything else, and there's nothing there. When you fire up the example you just get a blank frame with an input field and whatever I type in it does nothing. In the code I can only see handling of incoming messages, but nothing about joining a chan (technically that would be updating presence), or sending a message to one.

**Comment by silverbucket** [comment]
@skddc yeah that's why I said "It connects to a server... doesn't do much other than that." :) it's very basic. What was the missing element? If you don't want to add some docs somewhere, we should make a note of it here so that I can do so when I get a chance.

**Comment by skddc** [comment]
Hmm, I'm a bit unclear on what exactly were we supposed to test/implement then? Just the pure connecting to a server?

Btw, I just saw that the API docs include an [update](https://github.com/sockethub/sockethub-platform-xmpp/blob/master/API.md#xmppupdatejob) method for presence updates, so I would assume that this can somehow be used already, no?

**Comment by silverbucket** [comment]
@skddc I don't understand your first question - and yes anything that is documented should be working. 

I'm wondering what you did to get it working, you originally were unable to connect and then you figured it out, so would be good to make note of that here.

**Comment by silverbucket** [comment]
The example is just an example, I didn't have time to implement an XMPP app with a list of friends and being able to select and write to them. You can send messages if you type in the user address (if i remember correctly). The real test would be when Hyperchannel attempts to use it, so I ported it during hackerbeach but never actually got anyone testing it until now. So now is the testing.

**Comment by skddc** [comment]
> I'm wondering what you did to get it working, you originally were unable to connect and then you figured it out, so would be good to make note of that here.

I'm still unable to connect to my local Prosody with its default config. I didn't change anything for it to work with the 5apps one. I don't know of any difference in configuration between, so I suspect the SH platform requires TLS, but I'm not sure. The fact that `secure` isn't a valid property for XMPP servers (but for IRC ones) would also hint at that.

> I don't understand your first question

You wrote earlier in this issue that this was "ready for testing several months ago", and then, upon me asking about how to use this from Hyperchannel, that I should look at the example for usage instructions. Then I looked and there was nothing but the server connection. So I'm just unclear on what exactly was/is ready for testing. I don't yet understand SH well enough for it to be clear to me.

**Comment by silverbucket** [comment]
@skddc hopefully my last comment clarified about testing.

**Comment by skddc** [comment]
So, what would one `emit` from the Sockethub client in order for it to be routed to that `update` method in the platform code? A channel join in the MUC spec is a presence update with the channel JID plus nickname (and potentially password) as the `to` property:

https://xmpp.org/extensions/xep-0045.html#registrar-querytypes-join

**Comment by skddc** [comment]
Ah, and a part/exit would be the same, but including a specific `type` attr:

> The presence stanza used to exit a room MUST possess a 'type' attribute whose value is "unavailable". A MUC service MUST NOT treat a presence stanza with a 'type' attribute whose value is other than "unavailable" (e.g., a presence probe) as a request to exit the room.

**Comment by silverbucket** [comment]
I'm not sure why you're bringing in XMPP protocol, when the whole point of the AS API is to remove protocol specifics as much as possible. So you can't really use XMPP docs as a 1 to 1 matchup. We can talk about what's implemented using the xmpp module(s), and what the AS objects should look like. Joining channels is not currently implemented, but it should be simple enough to add we just need to figure out the way to do it. 

If you look at the IRC module, which does have rooms implemented, you'll see the `@type` (which is the AS2.0 version of a verb, which is what maps to the functions in the platform file) `join` which joins a channel. 

XMPP platform supports adding/removing friends, sending/receiving messages, updating presence.

**Comment by skddc** [comment]
> XMPP platform supports adding/removing friends, sending/receiving messages, updating presence.

Yes, and I pointed to the spec asking how I would update presence in the way that MUC needs for joining a channel. Or update any presence in any way. I'm asking how to use the platform's presence update function from the SH client:

> what would one emit from the Sockethub client in order for it to be routed to that update method in the platform code?

**Comment by skddc** [comment]
> Joining channels is not currently implemented, but it should be simple enough to add we just need to figure out the way to do it.

Hence my explanation, in case it's not currently possible with the existing presence update function:

> A channel join in the MUC spec is a presence update with the channel JID plus nickname (and potentially password) as the to property:
> 
> https://xmpp.org/extensions/xep-0045.html#registrar-querytypes-join

**Comment by skddc** [comment]
In this example from the linked XEP, "coven@chat.shakespeare.lit" is the channel JID, while "thirdwitch" is the nickname (which can be different from the username/JID):

```xml
<presence to='coven@chat.shakespeare.lit/thirdwitch'>
  <x xmlns='http://jabber.org/protocol/muc'/>
</presence>
```

**Comment by silverbucket** [comment]
Is it not yet clear how to send messages? The Sockethub Client wiki page + the API.md should be enough info to figure it out. If something is unclear please help me to improve the docs.

**Comment by skddc** [comment]
Yes, it is indeed still unclear to me how to send the message I asked about (presence update, plus presence update with specific `to` attribute or whatever that would be in SH/AS vocab). I cannot help improve the docs if I don't entirely understand the usage.

From the API doc for presence: https://github.com/sockethub/sockethub-platform-xmpp/blob/master/API.md#XMPP+update

```js
{
  context: 'xmpp',
  '@type': 'update',
  actor: {
    '@id': 'user@host.org/Home'
  },
  object: {
    '@type': 'presence'
    presence: 'chat',
    content: '...clever saying goes here...'
  }
}
```

And here's what I know as an app developer I need to actually send to the XMPP server:

```xml
<presence to='coven@chat.shakespeare.lit/thirdwitch'>
  <x xmlns='http://jabber.org/protocol/muc'/>
</presence>
```

Little of the information in the SH object above maps the information in the XML code below. In general, these questions arise from the doc:

1. How can I find out the meaning and potential values of the `presence` property (does "chat" mean MUC or is it the [show](https://tools.ietf.org/html/rfc6121#section-4.7.2.1) attribute?)
2. How can I find out the meaning of the `content` property? Does "clever saying" mean it's a presence [status](https://tools.ietf.org/html/rfc6121#section-4.7.2.2)?
3. How can I add the `to` attribute/value (and can I then omit the `presence` and `content` properties)?

I understand that Sockethub's whole idea is to *not* use the underlying protocols' vocab/props, but if an app developer wants to send a presence update, they still need to know how the SH/AS vocab maps to the XMPP one, or at least what the object properties mean exactly and what values make sense.

Maybe it would make sense to actually create schemas with validation, and more importantly, descriptions for those AS objects? That way, we could e.g. add links to relevant specs etc. in the description, and if a property has a certain set of allowed values (e.g. the presence "show" state), then it could also reject invalid ones.

**Comment by skddc** [comment]
... btw, I only just saw that the API doc changed in e42abe8f6cc1040bd46ba97f7eacdfed57c5c4bc yesterday. That was also playing a part in the confusion, because it had entirely different properties (`platform` vs. `context`). Thanks for fixing those!

**Comment by silverbucket** [comment]
> (platform vs. context e.g.)

That's AS1 vs AS2, leftover from before the switch.

**Comment by silverbucket** [comment]
@skddc have you tried sending a presence update to a room target?

**Comment by silverbucket** [comment]
@skddc or rather, it likely won't work right away as some of the code needs to change, but how should it look? You tell me. You have actors, objects and targets. You have the update object, so I would assume a target needs to be added.

**Comment by skddc** [comment]
Ok, so directed presence is not possible yet. That's one of the answers I was looking for (question 3) and completely fine. It just wasn't clear, because the docs don't explain the actual functionality (yet). Hence also questions 1 and 2 (which are still open), and my wondering if those objects could/should be defined in schemas as well (see also [my comment in the docs issue](https://github.com/sockethub/sockethub-platform-xmpp/issues/1#issuecomment-296930323).

Regarding directed presence, i.e. the `to` attribute: there are two use cases for this in XMPP as per spec. One is joining MUC channels and the other one is sending those to a specific user. I think for MUC joins a new `@type` with `join` makes sense, which would then accept a channel target. Not sure about adding the nickname to the target, same as the XMPP JID, but probably makes sense (as if you use it from actor, then you can't choose different nicks in different channels).

**Comment by silverbucket** [comment]
> How can I find out the meaning and potential values of the presence property (does "chat" mean MUC or is it the show attribute?)

I don't know, I'm not knowledgable about XMPP, so you're going to have to lead the way here. The values `available` and `chat` are used, or a user-defined string. I don't know what other things XMPP likes to hear from this property. Probably something like `offline` too?

> How can I find out the meaning of the content property? Does "clever saying" mean it's a presence status?

Yes, status was the original property, but in an effort to continue to simplify and go more in line with AS2 generic objects, I'm going with properties that fit pre-defined ones like `content` (e.q. an article object might have the content of the article, or a message object would have the content of the message being sent). So, we only translate to protocol-specific properties within the platform and not in the AS object. But this is still not solidified at all and could probably be improved further. 

BTW the answers to both of the above questions are pretty easy to see in this part of the code:
https://github.com/sockethub/sockethub-platform-xmpp/blob/master/index.js#L461-L468

> How can I add the to attribute/value (and can I then omit the presence and content properties)?

> Regarding directed presence, i.e. the to attribute: there are two use cases for this in XMPP as per spec. One is joining MUC channels and the other one is sending those to a specific user. I think for MUC joins a new @type with join makes sense, which would then accept a channel target. Not sure about adding the nickname to the target, same as the XMPP JID, but probably makes sense (as if you use it from actor, then you can't choose different nicks in different channels).

This would be a target.

(just an example, doesn't work like this yet)
```
{
  '@type': "join",
  actor: "xmpp://foobar@example.org/Home",
  target: "xmpp://example.org/Kosmos"   // or however a room should be defined.
}
```

Join is already an established type, we use it in the IRC platform. It's not implemented for XMPP yet, because it's unclear how we can join rooms using the node XMPP module(s). Again I'm not knowledgable about XMPP, I know much more about the way IRC works and was able to handle a lot more in that regard, but XMPP was never something I knew much about and Niklas was the only person who helped me with Sockethub development in this regard. It would make sense for you, or someone else who knows about XMPP, to lead the way while I can guide you about sockethub specific stuff and AS object handling. 

The node-simple-xmpp module wraps the node-xmpp module and is fairly simple, so features can be easily added to it to facilitate what we need. At this point it seems like the presence functionality method is not designed to handle room joins.

**Comment by silverbucket** [comment]
Let's continue in https://github.com/sockethub/sockethub-platform-xmpp/issues/6

**Comment by skddc** [comment]
For reference, the unmerged Hyperchannel code that is working with the remote server, but not the local one, can be found here: https://github.com/67P/hyperchannel/blob/feature/41-xmpp_support/app/services/sockethub-xmpp.js#L21-L51
